[phases.setup]
cmds = ["echo 'cache-bust-2026-05-13'"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["rm -rf .next/cache node_modules/.cache && npm install --legacy-peer-deps && npm run build"]

[start]
cmd = "npx next start -p 3000"
