[phases.install]
cmds = ["npm install --legacy-peer-deps --include=dev"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npm run build && npx prisma migrate deploy && node prisma/seed.js; node dist/main"
